name: solstice
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  receive_sharing_intent:
    git:
      url: git://github.com/KasemJaffer/receive_sharing_intent
      # ref: master
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  shared_preferences: ^0.5.7+2
  scoped_model: ^1.0.1
  flutter_svg: ^0.22.0
  flutter_screenutil: ^2.3.0
  country_list_pick: ^1.0.0
  pin_entry_text_field: ^0.1.4
  flutter_slidable: ^0.5.7
  cached_network_image: ^2.1.0+1
  image_picker: ^0.8.4
  image_cropper: ^1.2.1
  http: ^0.13.3
  intl: ^0.17.0
  modal_progress_hud: ^0.1.3
  dotted_border:
  flushbar: ^1.10.4
  flutter_staggered_grid_view: 0.3.2
  transparent_image: ^1.0.0
  google_maps_flutter:
  shimmer:
  model_viewer:
  get_version: ^0.2.2
  geolocator:
  geocoding: ^2.0.0
  otp_text_field: ^1.0.1
  emoji_picker: 0.1.0
  google_place: ^0.4.0
  autocomplete_textfield: ^1.7.3
  permission_handler: ^6.0.1+1
  flutter_google_places: ^0.2.5
  firebase_crashlytics: ^2.1.1
  open_mail_app: ^0.2.0
  flutter_easyloading: ^2.0.0
  flutter_overlay_loader: ^0.0.2
 

  algolia: any

  photo_view: ^0.9.2
  cloud_firestore: 
  firebase_auth: ^2.0.0
  firebase_storage: ^9.0.0
  firebase_core:
  firebase_messaging: ^10.0.3
  # flutter_local_notifications: ^6.0.0
  flutter_local_notifications: 5.0.0
  # video_thumbnail: ^0.4.3
  path_provider: ^2.0.2
  video_player: ^2.2.3
  # chewie: ^1.2.2
  chewie: 1.0.0
  
  camera: ^0.9.2+2
  dotted_line: ^3.0.0
  video_editor: ^1.2.0

  numberpicker: ^2.1.1
  multi_image_picker: ^4.7.14
  flutter_absolute_path: ^1.0.6
  # receive_sharing_intent: ^1.4.5
  inview_notifier_list: ^2.0.0
  flutter_reorderable_list: ^1.1.0
  flutter_swipe_action_cell: ^2.1.1
  flutter_switch: ^0.3.2
  url_launcher: ^6.0.10
  # notification_permissions: ^0.6.1
  # firebase_dynamic_links: ^2.0.11
  firebase_dynamic_links: ^0.5.0+11
  share: ^2.0.4
  visibility_detector: ^0.2.2
  percent_indicator: ^3.4.0
  carousel_pro: ^1.0.0
  carousel_slider: ^2.2.0
  dots_indicator: ^2.1.0
  card_swiper : ^2.0.1
  overlay_group_avatar: ^0.0.2
  flutter_spinkit: ^4.1.2+1
  #webview_flutter: 2.0.4
  # flutter_reorderable_list: ^1.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: epilogue_light
      fonts:
        - asset: assets/fonts/epilogue_light.ttf
    - family: epilogue_medium
      fonts:
        - asset: assets/fonts/epilogue_medium.ttf
    - family: epilogue_regular
      fonts:
        - asset: assets/fonts/epilogue_regular.ttf
    - family: epilogue_semibold
      fonts:
        - asset: assets/fonts/epilogue_semibold.ttf
    - family: epilogue_bold
      fonts:
        - asset: assets/fonts/epilogue_bold.ttf
    - family: tahu
      fonts:
        - asset: assets/fonts/tahu.ttf
    - family: open_saucesans_regular
      fonts:
        - asset: assets/fonts/open_saucesans_regular.ttf
    - family: roboto_regular
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
    - family: SFProText
      fonts:
        - asset: assets/fonts/FontsFree-Net-SFProText-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
      


  assets:
    - assets/images/
    - assets/front_body/
    - assets/back_body/
    - assets/wallet/





  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
